using IMIS.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IMIS.Persistence.SeedConfigurations
{
    public class AuditorOfficeConfiguration : IEntityTypeConfiguration<AuditorOffices>
    {
        public void Configure(EntityTypeBuilder<AuditorOffices> builder)
        {
            builder.HasData(
            // Team 1 - Department of Surgery
            new AuditorOffices { Id = 1, AuditorId = 19, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 2, AuditorId = 34, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 3, AuditorId = 26, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 4, AuditorId = 54, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 5, AuditorId = 15, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 6, AuditorId = 31, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 2 - EFMD - Mechanical Works Section
            new AuditorOffices { Id = 7, AuditorId = 14, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 8, AuditorId = 61, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 9, AuditorId = 41, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 10, AuditorId = 58, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 11, AuditorId = 16, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 12, AuditorId = 8, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
         
            // Team 3 - Peritoneal Dialysis Clinic
            new AuditorOffices { Id = 14, AuditorId = 17, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 15, AuditorId = 28, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 16, AuditorId = 60, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 17, AuditorId = 11, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 18, AuditorId = 78, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 19, AuditorId = 39, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 4 - Health Emergency Manangement Staff
            new AuditorOffices { Id = 20, AuditorId = 27, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 21, AuditorId = 49, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 22, AuditorId = 69, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 23, AuditorId = 74, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 24, AuditorId = 29, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 25, AuditorId = 57, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 5 - Health Information Management Department
             new AuditorOffices { Id = 26, AuditorId = 9, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 27, AuditorId = 53, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 28, AuditorId = 84, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 29, AuditorId = 82, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 30, AuditorId = 40, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 31, AuditorId = 33, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 6 - Mechanical Works Department - Elevator Unit
             new AuditorOffices { Id = 32, AuditorId = 20, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 33, AuditorId = 66, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 34, AuditorId = 71, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 35, AuditorId = 75, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 36, AuditorId = 18, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 37, AuditorId = 79, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

             // Team 7 - Department of Internal Medicine
             new AuditorOffices { Id = 39, AuditorId = 30, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 40, AuditorId = 48, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 41, AuditorId = 46, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 42, AuditorId = 47, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 43, AuditorId = 38, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 44, AuditorId = 42, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 8 - Health Information Management Department - Out-Patient Department
            new AuditorOffices { Id = 45, AuditorId = 24, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 46, AuditorId = 62, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 47, AuditorId = 76, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 48, AuditorId = 36, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 49, AuditorId = 3, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 50, AuditorId = 72, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 9 - Pay Admitting Unit
            new AuditorOffices { Id = 51, AuditorId = 55, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 52, AuditorId = 59, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 53, AuditorId = 37, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 54, AuditorId = 12, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 55, AuditorId = 10, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 56, AuditorId = 68, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 10 - Dental Department
            new AuditorOffices { Id = 57, AuditorId = 52, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true }, 
            new AuditorOffices { Id = 58, AuditorId = 65, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 59, AuditorId = 80, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 60, AuditorId = 21, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 61, AuditorId = 43, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 62, AuditorId = 77, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 11 - Emergency Department - Medical/Nursing
            new AuditorOffices { Id = 63, AuditorId = 63, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 64, AuditorId = 73, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 65, AuditorId = 6, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 66, AuditorId = 64, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 67, AuditorId = 44, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 12 - Department of Obstetics-Gynecology
            new AuditorOffices { Id = 68, AuditorId = 7, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 69, AuditorId = 45, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 70, AuditorId = 56, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 71, AuditorId = 13, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 72, AuditorId = 25, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 73, AuditorId = 23, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 13 - Budget Department
            new AuditorOffices { Id = 74, AuditorId = 51, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 75, AuditorId = 50, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 76, AuditorId = 81, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 77, AuditorId = 22, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 78, AuditorId = 70, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 79, AuditorId = 32, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 1 - Sec. Ona Wing
            new AuditorOffices { Id = 80, AuditorId = 19, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true }, 
            new AuditorOffices { Id = 81, AuditorId = 34, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 82, AuditorId = 26, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 83, AuditorId = 54, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 84, AuditorId = 15, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 85, AuditorId = 31, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 2 - Mechanical Works Section - Medical Oxygen Plant Unit
            new AuditorOffices { Id = 86, AuditorId = 14, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 87, AuditorId = 61, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 89, AuditorId = 41, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 90, AuditorId = 58, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 91, AuditorId = 16, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 92, AuditorId = 8, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 3 - Oncology Ward
            new AuditorOffices { Id = 93, AuditorId = 17, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 94, AuditorId = 28, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 95, AuditorId = 60, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 96, AuditorId = 11, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 97, AuditorId = 78, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 98, AuditorId = 39, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 4 - Public Assistance and Complaint Desk
            new AuditorOffices { Id = 99, AuditorId = 27, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 100, AuditorId = 49, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 101, AuditorId = 69, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 102, AuditorId = 74, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 103, AuditorId = 29, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 104, AuditorId = 57, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 5 - Integrated Hospital Operations and Management Program
            new AuditorOffices { Id = 105, AuditorId = 9, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 106, AuditorId = 53, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 107, AuditorId = 84, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 108, AuditorId = 82, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 109, AuditorId = 40, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 110, AuditorId = 33, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 6 - Physical Plant Section - Housekeeping Unit
            new AuditorOffices { Id = 111, AuditorId = 20, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 112, AuditorId = 66, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 113, AuditorId = 71, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 114, AuditorId = 75, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 115, AuditorId = 18, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 116, AuditorId = 79, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 7 - Medicine Ward
            new AuditorOffices { Id = 117, AuditorId = 30, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 118, AuditorId = 48, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 119, AuditorId = 46, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 120, AuditorId = 47, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 121, AuditorId = 38, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 122, AuditorId = 42, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 8 - Out-Patient Department - Medical/Nursing
            new AuditorOffices { Id = 123, AuditorId = 24, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 124, AuditorId = 62, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 125, AuditorId = 76, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 126, AuditorId = 36, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 127, AuditorId = 3, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 128, AuditorId = 72, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 9 - Delivery Room - Medical/Nursing
            new AuditorOffices { Id = 129, AuditorId = 55, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 130, AuditorId = 59, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 131, AuditorId = 37, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 132, AuditorId = 12, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 133, AuditorId = 10, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 134, AuditorId = 68, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 10 - Department of Diagnostic and Therapeutic Radiology
            new AuditorOffices { Id = 135, AuditorId = 52, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 136, AuditorId = 65, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 137, AuditorId = 80, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 138, AuditorId = 21, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 139, AuditorId = 43, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 140, AuditorId = 77, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 11 - Department of Pathology - Anatomic and Clinical Laboratory
            new AuditorOffices { Id = 141, AuditorId = 63, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 142, AuditorId = 73, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 143, AuditorId = 6, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 144, AuditorId = 64, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 145, AuditorId = 44, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 12 - Obstetrics and Gynecology Ward
            new AuditorOffices { Id = 146, AuditorId = 7, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 147, AuditorId = 45, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 148, AuditorId = 56, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 149, AuditorId = 13, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 150, AuditorId = 25, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 151, AuditorId = 23, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 13 - Procurement Department and Bids and Awards Committee
            new AuditorOffices { Id = 152, AuditorId = 51, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 153, AuditorId = 50, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 154, AuditorId = 81, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 155, AuditorId = 22, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 156, AuditorId = 70, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 157, AuditorId = 32, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 1 - Surgery Wing
            new AuditorOffices { Id = 158, AuditorId = 19, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 159, AuditorId = 34, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 160, AuditorId = 26, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 161, AuditorId = 54, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 162, AuditorId = 15, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 163, AuditorId = 31, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 2 - EFMD - Biomedical Section
            new AuditorOffices { Id = 164, AuditorId = 14, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 165, AuditorId = 61, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 166, AuditorId = 41, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 167, AuditorId = 58, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 168, AuditorId = 16, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 169, AuditorId = 8, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 3 - Mental Health Unit
            new AuditorOffices { Id = 170, AuditorId = 17, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 171, AuditorId = 28, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 172, AuditorId = 60, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 173, AuditorId = 11, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 174, AuditorId = 78, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 175, AuditorId = 39, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 4 - Research Institute
            new AuditorOffices { Id = 176, AuditorId = 27, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 177, AuditorId = 49, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 178, AuditorId = 69, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 179, AuditorId = 74, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 180, AuditorId = 29, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 181, AuditorId = 57, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

             // Team 5 - Medical Insurance Evaluation Unit
             new AuditorOffices { Id = 182, AuditorId = 9, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 183, AuditorId = 53, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 184, AuditorId = 84, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 185, AuditorId = 82, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 186, AuditorId = 40, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 187, AuditorId = 33, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

             // Team 6 - Pysical Plant - Laundry and Linen Unit
             new AuditorOffices { Id = 188, AuditorId = 20, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 189, AuditorId = 66, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 190, AuditorId = 71, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 191, AuditorId = 75, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 192, AuditorId = 18, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 193, AuditorId = 79, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

             // Team 7 - General Extension Ward
             new AuditorOffices { Id = 194, AuditorId = 30, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 195, AuditorId = 48, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 196, AuditorId = 46, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 197, AuditorId = 47, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 198, AuditorId = 38, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
             new AuditorOffices { Id = 199, AuditorId = 42, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 8 - Family and Community Medicine Department
            new AuditorOffices { Id = 200, AuditorId = 24, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 201, AuditorId = 62, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 202, AuditorId = 76, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 203, AuditorId = 36, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 204, AuditorId = 3, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 205, AuditorId = 72, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 9 - Oparating Room & Post Anesthesia Care Unit
            new AuditorOffices { Id = 206, AuditorId = 55, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 207, AuditorId = 59, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 208, AuditorId = 37, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 209, AuditorId = 12, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 210, AuditorId = 10, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 211, AuditorId = 68, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 10 - TB Center
            new AuditorOffices { Id = 212, AuditorId = 52, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 213, AuditorId = 65, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 214, AuditorId = 80, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 215, AuditorId = 21, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 216, AuditorId = 43, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 217, AuditorId = 77, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 11 - Health Information Management Department - Admitting Section
            new AuditorOffices { Id = 218, AuditorId = 63, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 219, AuditorId = 73, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 220, AuditorId = 6, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 221, AuditorId = 64, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 222, AuditorId = 44, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 12 - Department of Pediatrics
            new AuditorOffices { Id = 223, AuditorId = 7, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 224, AuditorId = 45, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 225, AuditorId = 56, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 226, AuditorId = 13, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 227, AuditorId = 25, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 228, AuditorId = 23, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Team 13 - Material and Supply Management Department
            new AuditorOffices { Id = 229, AuditorId = 51, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 230, AuditorId = 50, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 231, AuditorId = 81, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 232, AuditorId = 22, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 233, AuditorId = 70, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 234, AuditorId = 32, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Audit Team 1 -13
            new AuditorOffices { Id = 235, AuditorId = 2, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 236, AuditorId = 2, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 237, AuditorId = 2, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 238, AuditorId = 2, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 239, AuditorId = 2, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 240, AuditorId = 2, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 241, AuditorId = 2, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 242, AuditorId = 2, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 243, AuditorId = 2, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 244, AuditorId = 2, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 245, AuditorId = 2, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 246, AuditorId = 2, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 247, AuditorId = 2, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 248, AuditorId = 2, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 249, AuditorId = 2, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 250, AuditorId = 2, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 251, AuditorId = 2, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 252, AuditorId = 2, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 253, AuditorId = 2, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 254, AuditorId = 2, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 255, AuditorId = 2, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 256, AuditorId = 2, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 257, AuditorId = 2, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 258, AuditorId = 2, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 259, AuditorId = 2, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 260, AuditorId = 2, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 261, AuditorId = 2, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 262, AuditorId = 2, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 263, AuditorId = 2, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 264, AuditorId = 2, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 265, AuditorId = 2, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 266, AuditorId = 2, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 267, AuditorId = 2, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 268, AuditorId = 2, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 269, AuditorId = 2, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 270, AuditorId = 2, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 271, AuditorId = 2, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 272, AuditorId = 2, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 273, AuditorId = 2, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Audit Team 1 -13
            new AuditorOffices { Id = 274, AuditorId = 35, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 275, AuditorId = 35, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 276, AuditorId = 35, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 277, AuditorId = 35, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 278, AuditorId = 35, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 279, AuditorId = 35, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 280, AuditorId = 35, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 281, AuditorId = 35, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 282, AuditorId = 35, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 283, AuditorId = 35, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 284, AuditorId = 35, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 285, AuditorId = 35, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 286, AuditorId = 35, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 287, AuditorId = 35, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 288, AuditorId = 35, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 289, AuditorId = 35, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 290, AuditorId = 35, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 291, AuditorId = 35, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 292, AuditorId = 35, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 293, AuditorId = 35, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 294, AuditorId = 35, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 295, AuditorId = 35, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 296, AuditorId = 35, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 297, AuditorId = 35, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 298, AuditorId = 35, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 299, AuditorId = 35, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 300, AuditorId = 35, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 301, AuditorId = 35, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 302, AuditorId = 35, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 303, AuditorId = 35, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 304, AuditorId = 35, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 305, AuditorId = 35, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 306, AuditorId = 35, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 307, AuditorId = 35, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 308, AuditorId = 35, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 309, AuditorId = 35, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 310, AuditorId = 35, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 311, AuditorId = 35, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 312, AuditorId = 35, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Audit Team 1 -13
            new AuditorOffices { Id = 313, AuditorId = 67, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 314, AuditorId = 67, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 315, AuditorId = 67, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 316, AuditorId = 67, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 317, AuditorId = 67, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 318, AuditorId = 67, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 319, AuditorId = 67, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 320, AuditorId = 67, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 321, AuditorId = 67, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 322, AuditorId = 67, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 323, AuditorId = 67, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 324, AuditorId = 67, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 325, AuditorId = 67, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 326, AuditorId = 67, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 327, AuditorId = 67, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 328, AuditorId = 67, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 329, AuditorId = 67, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 330, AuditorId = 67, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 331, AuditorId = 67, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 332, AuditorId = 67, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 333, AuditorId = 67, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 334, AuditorId = 67, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 335, AuditorId = 67, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 336, AuditorId = 67, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 337, AuditorId = 67, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 338, AuditorId = 67, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 339, AuditorId = 67, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 340, AuditorId = 67, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 341, AuditorId = 67, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 342, AuditorId = 67, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 343, AuditorId = 67, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 344, AuditorId = 67, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 345, AuditorId = 67, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 346, AuditorId = 67, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 347, AuditorId = 67, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 348, AuditorId = 67, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 349, AuditorId = 67, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 350, AuditorId = 67, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 351, AuditorId = 67, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Audit Team 1 -13
            new AuditorOffices { Id = 352, AuditorId = 83, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 353, AuditorId = 83, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 354, AuditorId = 83, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 355, AuditorId = 83, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 356, AuditorId = 83, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 357, AuditorId = 83, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 358, AuditorId = 83, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 359, AuditorId = 83, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 360, AuditorId = 83, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 361, AuditorId = 83, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 362, AuditorId = 83, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 363, AuditorId = 83, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 364, AuditorId = 83, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 365, AuditorId = 83, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 366, AuditorId = 83, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 367, AuditorId = 83, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 368, AuditorId = 83, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 369, AuditorId = 83, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 370, AuditorId = 83, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 371, AuditorId = 83, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 372, AuditorId = 83, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 373, AuditorId = 83, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 374, AuditorId = 83, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 375, AuditorId = 83, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 376, AuditorId = 83, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 377, AuditorId = 83, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 378, AuditorId = 83, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 379, AuditorId = 83, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 380, AuditorId = 83, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 381, AuditorId = 83, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 382, AuditorId = 83, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 383, AuditorId = 83, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 384, AuditorId = 83, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 385, AuditorId = 83, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 386, AuditorId = 83, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 387, AuditorId = 83, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 388, AuditorId = 83, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 389, AuditorId = 83, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 390, AuditorId = 83, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Audit Team 1 -13
            new AuditorOffices { Id = 391, AuditorId = 5, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 392, AuditorId = 5, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 393, AuditorId = 5, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 394, AuditorId = 5, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 395, AuditorId = 5, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 396, AuditorId = 5, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 397, AuditorId = 5, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 398, AuditorId = 5, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 399, AuditorId = 5, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 400, AuditorId = 5, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 401, AuditorId = 5, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 402, AuditorId = 5, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 403, AuditorId = 5, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 404, AuditorId = 5, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 405, AuditorId = 5, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 406, AuditorId = 5, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 407, AuditorId = 5, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 408, AuditorId = 5, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 409, AuditorId = 5, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 410, AuditorId = 5, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 411, AuditorId = 5, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 412, AuditorId = 5, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 413, AuditorId = 5, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 414, AuditorId = 5, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 415, AuditorId = 5, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 416, AuditorId = 5, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 417, AuditorId = 5, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 418, AuditorId = 5, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 419, AuditorId = 5, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 420, AuditorId = 5, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 421, AuditorId = 5, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 422, AuditorId = 5, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 423, AuditorId = 5, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 424, AuditorId = 5, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 425, AuditorId = 5, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 426, AuditorId = 5, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 427, AuditorId = 5, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 428, AuditorId = 5, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 429, AuditorId = 5, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },

            // Audit Team 1 -13
            new AuditorOffices { Id = 430, AuditorId = 4, OfficeId = 9, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 431, AuditorId = 4, OfficeId = 165, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 432, AuditorId = 4, OfficeId = 159, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 433, AuditorId = 4, OfficeId = 166, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 434, AuditorId = 4, OfficeId = 19, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 435, AuditorId = 4, OfficeId = 116, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 436, AuditorId = 4, OfficeId = 8, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 437, AuditorId = 4, OfficeId = 29, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 438, AuditorId = 4, OfficeId = 169, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 439, AuditorId = 4, OfficeId = 18, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 440, AuditorId = 4, OfficeId = 170, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 441, AuditorId = 4, OfficeId = 10, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 442, AuditorId = 4, OfficeId = 41, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 443, AuditorId = 4, OfficeId = 33, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 444, AuditorId = 4, OfficeId = 171, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 445, AuditorId = 4, OfficeId = 34, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 446, AuditorId = 4, OfficeId = 127, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 447, AuditorId = 4, OfficeId = 125, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 448, AuditorId = 4, OfficeId = 172, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 449, AuditorId = 4, OfficeId = 23, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 450, AuditorId = 4, OfficeId = 173, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 451, AuditorId = 4, OfficeId = 28, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 452, AuditorId = 4, OfficeId = 17, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 453, AuditorId = 4, OfficeId = 16, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 454, AuditorId = 4, OfficeId = 26, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 455, AuditorId = 4, OfficeId = 38, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 456, AuditorId = 4, OfficeId = 174, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 457, AuditorId = 4, OfficeId = 120, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 458, AuditorId = 4, OfficeId = 83, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 459, AuditorId = 4, OfficeId = 156, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 460, AuditorId = 4, OfficeId = 158, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 461, AuditorId = 4, OfficeId = 175, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 462, AuditorId = 4, OfficeId = 58, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 463, AuditorId = 4, OfficeId = 176, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 464, AuditorId = 4, OfficeId = 177, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 465, AuditorId = 4, OfficeId = 87, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 466, AuditorId = 4, OfficeId = 99, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 467, AuditorId = 4, OfficeId = 11, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true },
            new AuditorOffices { Id = 468, AuditorId = 4, OfficeId = 178, IsDeleted = false, PgsPeriodId = 1, IsOfficeHead = true }







            );
        }
    }
}
