using IMIS.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IMIS.Persistence.SeedConfigurations
{
    public class OfficeConfiguration : IEntityTypeConfiguration<Office>
    {
        public void Configure(EntityTypeBuilder<Office> builder)
        {
            builder.HasData(
                new Office { Id = 1, Name = "Medical Center Chief", OfficeTypeId = 1, ParentOfficeId = null, IsActive = true, IsDeleted = false },
                new Office { Id = 2, Name = "Medical Service", OfficeTypeId = 1, ParentOfficeId = null, IsActive = true, IsDeleted = false },
                new Office { Id = 3, Name = "Nursing Service", OfficeTypeId = 1, ParentOfficeId = null, IsActive = true, IsDeleted = false },
                new Office { Id = 4, Name = "Hospital Operations and Patient Support Service", OfficeTypeId = 1, ParentOfficeId = null, IsActive = true, IsDeleted = false },
                new Office { Id = 5, Name = "Finance Service", OfficeTypeId = 1, ParentOfficeId = null, IsActive = true, IsDeleted = false },
                new Office { Id = 6, Name = "Lateral Entry", OfficeTypeId = 1, ParentOfficeId = null, IsActive = true, IsDeleted = false },
                new Office { Id = 7, Name = "Allied/Ancillary", OfficeTypeId = 1, ParentOfficeId = null, IsActive = true, IsDeleted = false },


                new Office { Id = 8, Name = "Department of Internal Medicine", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 9, Name = "Department of Surgery", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 10, Name = "Department of Obstetics-Gynecology", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 11, Name = "Department of Pediatrics", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 12, Name = "Department of Anesthesiology", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 13, Name = "Physical Medicine and Rehabilitation Department", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 14, Name = "Out-Patient Department", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 15, Name = "Emergency Department", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 16, Name = "Department of Pathology", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 17, Name = "Department of Diagnostic and Therapuetic Radiology", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 18, Name = "Dental Department", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },


                new Office { Id = 19, Name = "Health Information Management Department", OfficeTypeId = 3, ParentOfficeId = 7, IsActive = true, IsDeleted = false },
                new Office { Id = 20, Name = "Medical Social Work Department", OfficeTypeId = 3, ParentOfficeId = 7, IsActive = true, IsDeleted = false },
                new Office { Id = 21, Name = "Nutrition and Dietetics Department", OfficeTypeId = 3, ParentOfficeId = 7, IsActive = true, IsDeleted = false },
                new Office { Id = 22, Name = "Pharmacy Department", OfficeTypeId = 3, ParentOfficeId = 7, IsActive = true, IsDeleted = false },


                new Office { Id = 23, Name = "Medicine Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 24, Name = "Pediatrics Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 25, Name = "Surgery Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 26, Name = "OB-Gynecology Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 27, Name = "Operating Room", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 28, Name = "Delivery Room", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 29, Name = "Out-Patient Department", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 30, Name = "Emergency Department", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 31, Name = "Pay Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 32, Name = "Orthopedic, Ophthalmology, and Urology Wards", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 33, Name = "Sec. Ona Wing", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 34, Name = "Oncology Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 35, Name = "Central Supply and Sterilization Room", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 36, Name = "Mental Health Unit", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },


                new Office { Id = 37, Name = "Human Resource Management Department", OfficeTypeId = 3, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 38, Name = "Procurement Department", OfficeTypeId = 3, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 39, Name = "Materials and Supplies Management Department", OfficeTypeId = 3, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 40, Name = "Engineering and Facilities Management Department", OfficeTypeId = 3, ParentOfficeId = 4, IsActive = true, IsDeleted = false },


                new Office { Id = 41, Name = "Budget Department", OfficeTypeId = 3, ParentOfficeId = 5, IsActive = true, IsDeleted = false },
                new Office { Id = 42, Name = "Accounting department", OfficeTypeId = 3, ParentOfficeId = 5, IsActive = true, IsDeleted = false },
                new Office { Id = 43, Name = "Cash Operations Department", OfficeTypeId = 3, ParentOfficeId = 5, IsActive = true, IsDeleted = false },
                new Office { Id = 44, Name = "Medical Center Chief Office", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 45, Name = "CMPS Office", OfficeTypeId = 3, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 46, Name = "Bureau of Quarantine", OfficeTypeId = 3, ParentOfficeId = 6, IsActive = true, IsDeleted = false },
                new Office { Id = 47, Name = "Chief Nurse Office", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 48, Name = "TB Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 49, Name = "CAO Office", OfficeTypeId = 3, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 50, Name = "PUBLIC HEALTH UNIT-HEALTH PROMOTION UNIT", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 51, Name = "Auditor's Office", OfficeTypeId = 3, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 52, Name = "Extension Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 53, Name = "MHU-COVID Ext.", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 54, Name = "COVID Ext. Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 55, Name = "TB-CENTER", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 56, Name = "OHCC", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 57, Name = "OB/SURGERY/ORTHO Extension Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 58, Name = "General Extension Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 59, Name = "ICU Complex", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 60, Name = "COVEX I", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 61, Name = "OB GYNE/SURGERY Ward", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 62, Name = "Department of Emergency Medicine", OfficeTypeId = 3, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 63, Name = "Transfer Treatment Monitoring Facility", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 64, Name = "Family Medicine Department", OfficeTypeId = 3, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 65, Name = "Billing and Claims Section", OfficeTypeId = 3, ParentOfficeId = 5, IsActive = true, IsDeleted = false },
                new Office { Id = 66, Name = "Public Health Section", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 67, Name = "Finance Office", OfficeTypeId = 3, ParentOfficeId = 5, IsActive = true, IsDeleted = false },
                new Office { Id = 68, Name = "Cancer Institute", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 69, Name = "Women's Health Center", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 70, Name = "Section of Dermatology and Venereology", OfficeTypeId = 3, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 71, Name = "College of Medicine Department", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 72, Name = "Family Medicine Department", OfficeTypeId = 3, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 73, Name = "Ophthalmology Department", OfficeTypeId = 3, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 74, Name = "Medical Insurance Evaluation and Reconcillation Unit", OfficeTypeId = 3, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 75, Name = "Professional,Education,Training and Development Unit", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 76, Name = "Soccsksargen Regional Blood Center", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 77, Name = "Trauma Center", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 78, Name = "Burn Center", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 79, Name = "Cardiovascular Center", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 80, Name = "Renal Care and Transplant Unit", OfficeTypeId = 3, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 81, Name = "Cancer Institute", OfficeTypeId = 3, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 82, Name = "Medicine Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 8, IsActive = true, IsDeleted = false },
                new Office { Id = 83, Name = "Mental Health Unit", OfficeTypeId = 4, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 84, Name = "Hemodialysis Unit", OfficeTypeId = 4, ParentOfficeId = 8, IsActive = true, IsDeleted = false },
                new Office { Id = 85, Name = "Heart Station", OfficeTypeId = 4, ParentOfficeId = 8, IsActive = true, IsDeleted = false },
                new Office { Id = 86, Name = "Section of Pulmonary Medicine", OfficeTypeId = 4, ParentOfficeId = 8, IsActive = true, IsDeleted = false },
                new Office { Id = 87, Name = "TB Center", OfficeTypeId = 4, ParentOfficeId = 8, IsActive = true, IsDeleted = false },
                new Office { Id = 88, Name = "Surgery Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 9, IsActive = true, IsDeleted = false },
                new Office { Id = 89, Name = "Burn Unit", OfficeTypeId = 4, ParentOfficeId = 9, IsActive = true, IsDeleted = false },
                new Office { Id = 90, Name = "Orthopedics", OfficeTypeId = 4, ParentOfficeId = 9, IsActive = true, IsDeleted = false },
                new Office { Id = 91, Name = "Ophthalmology", OfficeTypeId = 4, ParentOfficeId = 9, IsActive = true, IsDeleted = false },
                new Office { Id = 92, Name = "Urology", OfficeTypeId = 4, ParentOfficeId = 9, IsActive = true, IsDeleted = false },
                new Office { Id = 93, Name = "Otorhinolaryngology", OfficeTypeId = 4, ParentOfficeId = 9, IsActive = true, IsDeleted = false },
                new Office { Id = 94, Name = "OB-Gyrecology Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 10, IsActive = true, IsDeleted = false },
                new Office { Id = 95, Name = "Pediatric Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 11, IsActive = true, IsDeleted = false },
                new Office { Id = 96, Name = "Neonatal Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 11, IsActive = true, IsDeleted = false },
                new Office { Id = 97, Name = "Anatomic and Clinical Laboratory", OfficeTypeId = 4, ParentOfficeId = 16, IsActive = true, IsDeleted = false },
                new Office { Id = 98, Name = "Blood Bank", OfficeTypeId = 4, ParentOfficeId = 16, IsActive = true, IsDeleted = false },
                new Office { Id = 99, Name = "Admitting Section", OfficeTypeId = 4, ParentOfficeId = 19, IsActive = true, IsDeleted = false },
                new Office { Id = 100, Name = "HIM OPD", OfficeTypeId = 4, ParentOfficeId = 19, IsActive = true, IsDeleted = false },
                new Office { Id = 101, Name = "ER Satellite Pharmacy", OfficeTypeId = 4, ParentOfficeId = 22, IsActive = true, IsDeleted = false },
                new Office { Id = 102, Name = "OPD Satellite Pharmacy", OfficeTypeId = 4, ParentOfficeId = 22, IsActive = true, IsDeleted = false },
                new Office { Id = 103, Name = "Medicine Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 23, IsActive = true, IsDeleted = false },
                new Office { Id = 104, Name = "Hemodialysis Unit", OfficeTypeId = 4, ParentOfficeId = 23, IsActive = true, IsDeleted = false },
                new Office { Id = 105, Name = "Heart Station", OfficeTypeId = 4, ParentOfficeId = 23, IsActive = true, IsDeleted = false },
                new Office { Id = 106, Name = "Neonatal Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 24, IsActive = true, IsDeleted = false },
                new Office { Id = 107, Name = "Pediatric Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 24, IsActive = true, IsDeleted = false },
                new Office { Id = 108, Name = "Surgery Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 25, IsActive = true, IsDeleted = false },
                new Office { Id = 109, Name = "Burn Unit", OfficeTypeId = 4, ParentOfficeId = 25, IsActive = true, IsDeleted = false },
                new Office { Id = 110, Name = "OB-Gynecology Intensive Care Unit", OfficeTypeId = 4, ParentOfficeId = 26, IsActive = true, IsDeleted = false },
                new Office { Id = 111, Name = "Post Aresthetic Care Unit", OfficeTypeId = 4, ParentOfficeId = 27, IsActive = true, IsDeleted = false },
                new Office { Id = 112, Name = "CCTV Unit", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 113, Name = "Security Services (Contracted Out)", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 114, Name = "Motorpool Unit", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 115, Name = "Mechanical Maintenance Unit", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 116, Name = "Elevator Unit", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 117, Name = "Medical Oxygen Plant Unit", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 118, Name = "Laundry and Linen Unit", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 119, Name = "Housekeeping Unit", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 120, Name = "Biomedical Section", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 121, Name = "Electrical Section", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 122, Name = "Billing Unit", OfficeTypeId = 4, ParentOfficeId = 65, IsActive = true, IsDeleted = false },
                new Office { Id = 123, Name = "Claims Unit", OfficeTypeId = 4, ParentOfficeId = 65, IsActive = true, IsDeleted = false },
                new Office { Id = 124, Name = "Professional Education Training and Research Unit", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 125, Name = "Integrated Hospital Operations and Management Program", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 126, Name = "Legal Unit", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 127, Name = "Public Assistance and Complaint Desk", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 128, Name = "Surveillance Unit", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 129, Name = "Infectious Unit", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 130, Name = "HACT Office", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 131, Name = "OPD Surveillance", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 132, Name = "ER Surveillance", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 133, Name = "Temporary Treatment Monitoring Facility", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 134, Name = "TB ISO", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 135, Name = "OSM", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 136, Name = "HDU - Annex", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 137, Name = "Surgery", OfficeTypeId = 4, ParentOfficeId = 14, IsActive = true, IsDeleted = false },
                new Office { Id = 138, Name = "Hospital Infection Prevention and Control Unit", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 139, Name = "Social Hygiene and Treatment Hub", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 140, Name = "Hospital Epidemiology and Surveillance Unit", OfficeTypeId = 4, ParentOfficeId = 66, IsActive = true, IsDeleted = false },
                new Office { Id = 141, Name = "CATH LAB", OfficeTypeId = 4, ParentOfficeId = 27, IsActive = true, IsDeleted = false },
                new Office { Id = 142, Name = "Physical Plant", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 143, Name = "Newborn Screening", OfficeTypeId = 4, ParentOfficeId = 11, IsActive = true, IsDeleted = false },
                new Office { Id = 144, Name = "Plastic Surgery", OfficeTypeId = 4, ParentOfficeId = 9, IsActive = true, IsDeleted = false },
                new Office { Id = 145, Name = "Women's Health Center", OfficeTypeId = 4, ParentOfficeId = 10, IsActive = true, IsDeleted = false },
                new Office { Id = 146, Name = "PICU", OfficeTypeId = 4, ParentOfficeId = 24, IsActive = true, IsDeleted = false },
                new Office { Id = 147, Name = "Clinical Spiritual Care Unit", OfficeTypeId = 4, ParentOfficeId = 16, IsActive = true, IsDeleted = false },
                new Office { Id = 148, Name = "Security Management Unit", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 149, Name = "TTMF", OfficeTypeId = 4, ParentOfficeId = 45, IsActive = true, IsDeleted = false },
                new Office { Id = 150, Name = "Emergency Room", OfficeTypeId = 4, ParentOfficeId = 45, IsActive = true, IsDeleted = false },
                new Office { Id = 151, Name = "Diagnostic Evaluation Unit", OfficeTypeId = 4, ParentOfficeId = 45, IsActive = true, IsDeleted = false },
                new Office { Id = 152, Name = "Physical Therapy Section", OfficeTypeId = 4, ParentOfficeId = 13, IsActive = true, IsDeleted = false },
                new Office { Id = 153, Name = "Prosthetic and Orthotic Section", OfficeTypeId = 4, ParentOfficeId = 13, IsActive = true, IsDeleted = false },
                new Office { Id = 154, Name = "Brain and Spine Center", OfficeTypeId = 4, ParentOfficeId = 9, IsActive = true, IsDeleted = false },
                new Office { Id = 155, Name = "Dormitory Unit", OfficeTypeId = 4, ParentOfficeId = 40, IsActive = true, IsDeleted = false },
                new Office { Id = 156, Name = "Research Institute", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 157, Name = "Health Emergency Disaster Management Unit", OfficeTypeId = 4, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 158, Name = "Medical Insurance Evaluation Unit", OfficeTypeId = 4, ParentOfficeId = 45, IsActive = true, IsDeleted = false },
                new Office { Id = 159, Name = "Peritoneal Dialysis", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 160, Name = "Pallative Care Unit", OfficeTypeId = 4, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 161, Name = "Toxicology Unit", OfficeTypeId = 4, ParentOfficeId = 64, IsActive = true, IsDeleted = false },
                new Office { Id = 162, Name = "New Born Screening", OfficeTypeId = 4, ParentOfficeId = 24, IsActive = true, IsDeleted = false },
                new Office { Id = 163, Name = "Patient and Safety Unit", OfficeTypeId = 4, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 164, Name = "Credit and Collection Section", OfficeTypeId = 4, ParentOfficeId = 5, IsActive = true, IsDeleted = false },
                new Office { Id = 165, Name = "EFMD - Mechanical Works Section", OfficeTypeId = 2, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 166, Name = "Health Emergency Management Staff", OfficeTypeId = 2, ParentOfficeId = 1, IsActive = true, IsDeleted = false },
                new Office { Id = 167, Name = "Mechanical Works Department - Elevator Unit", OfficeTypeId = 2, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 168, Name = "Health Information Management Department - Out-Patient Department", OfficeTypeId = 2, ParentOfficeId = 7, IsActive = true, IsDeleted = false },
                new Office { Id = 169, Name = "Pay Admitting Unit", OfficeTypeId = 2, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 170, Name = "Emergency Department - Medical/Nursing", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 171, Name = "Mechanical Works Section - Medical Oxygen Plant Unit", OfficeTypeId = 2, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 172, Name = "Physical Plant Section - Housekeeping Unit", OfficeTypeId = 2, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 173, Name = "Out-Patient Department - Medical/Nursing", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 174, Name = "Surgery Wing", OfficeTypeId = 2, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 175, Name = "Physical Plant - Laundry and Linen unit", OfficeTypeId = 2, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 176, Name = "Family and Community Medicine Department", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 177, Name = "Operating Room & Post-Anesthesia Care Unit", OfficeTypeId = 2, ParentOfficeId = 3, IsActive = true, IsDeleted = false },
                new Office { Id = 178, Name = "Material and Supply Management Department", OfficeTypeId = 2, ParentOfficeId = 4, IsActive = true, IsDeleted = false },
                new Office { Id = 179, Name = "Head Women and Child Protection Unit", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 180, Name = "EEG", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false },
                new Office { Id = 181, Name = "SHTH", OfficeTypeId = 2, ParentOfficeId = 2, IsActive = true, IsDeleted = false }
            );
        }
    }
}
