using IMIS.Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;


public class UserConfiguration : IEntityTypeConfiguration<User>
{
    
    public void Configure(EntityTypeBuilder<User> builder)
    {
 
        var hasher = new PasswordHasher<IdentityUser>();
        string defaultPassword = "Abc123*@";

        builder.HasData(
            new User
            {
                Id = "f7cf5c73-16d9-4da8-9e0a-cc149b34fbbd",             
                UserName = "castillano.mrb",
                NormalizedUserName = "CASTILLANO.MRB",
                Email = "marcrejohncastillano@gmail.com",
                NormalizedEmail = "MARCREJOHNCASTILLANO@GMAIL.COM",
                PasswordHash = hasher.HashPassword(null, defaultPassword),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                LastName = "Castillano",
                FirstName = "Marc Rejohn",
                MiddleName = "Ballares",
                PhoneNumber = "09959283775",
            },
            new User
            {
                Id = "176bcfeb-f12a-4d42-b790-5d2312660801",                
                UserName = "rama.emg",
                NormalizedUserName = "RAMA.EMG",
                Email = "earlmaerama@gmail.com",
                NormalizedEmail = "EARLMAERAMA@GMAIL.COM",
                PasswordHash = hasher.HashPassword(null, defaultPassword),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                LastName = "Rama",
                FirstName = "Earlene Mae",
                MiddleName = "Gallos",
                PhoneNumber = "09128293036",
            },
            new User
            {
                Id = "fb385d60-eaee-4ea2-8bf1-b5cc0723c17a",              
                UserName = "pimentel.wb",
                NormalizedUserName = "PIMENTEL.WB",
                Email = "wilburpimentel09@gmail.com",
                NormalizedEmail = "WILBURPIMENTEL09@GMAIL.COM",
                PasswordHash = hasher.HashPassword(null, defaultPassword),
                ConcurrencyStamp = Guid.NewGuid().ToString(),
                LastName = "Pimentel",
                FirstName = "Wilbur",
                MiddleName = "Bello",
                PhoneNumber = "09069043375",
            },
             new User
             {
                 Id = "537d9fcd-b505-4f93-afc6-17eb8eddff83",
                 UserName = "Nolan",
                 NormalizedUserName = "NOLAN",
                 Email = "Nolan1234@gmail.com",
                 NormalizedEmail = "NOLAN1234@GMAIL.COM",
                 PasswordHash = hasher.HashPassword(null, defaultPassword),
                 ConcurrencyStamp = Guid.NewGuid().ToString(),
                 LastName = "Avanzado",
                 FirstName = "Nolan",
                 MiddleName = "",
                 PhoneNumber = "",                
             },
              new User
              {
                  Id = "743b9807-3441-47c1-9285-5ff8dfd7acb9",
                  UserName = "Sheila",
                  NormalizedUserName = "SHEILA",
                  Email = "Sheila1234@gmail.com",
                  NormalizedEmail = "SHEILA1234@GMAIL.COM",
                  PasswordHash = hasher.HashPassword(null, defaultPassword),
                  ConcurrencyStamp = Guid.NewGuid().ToString(),
                  LastName = "Mangelen",
                  FirstName = "Sheila farish",
                  MiddleName = "K.",
                  PhoneNumber = "",
              },
               new User
               {
                   Id = "7acb06ae-c2de-4fa1-8b62-53c1d63121f0",
                   UserName = "Johari",
                   NormalizedUserName = "JOHARI",
                   Email = "Johari1234@gmail.com",
                   NormalizedEmail = "JOHARI1234@GMAIL.COM",
                   PasswordHash = hasher.HashPassword(null, defaultPassword),
                   ConcurrencyStamp = Guid.NewGuid().ToString(),
                   LastName = "Casan",
                   FirstName = "Johari",
                   MiddleName = "P.",
                   PhoneNumber = "",
               },
                new User
                {
                    Id = "7eee5b08-df0d-4ac0-a8db-39d924dd30b7",
                    UserName = "Linda",
                    NormalizedUserName = "LINDA",
                    Email = "Linda1234@gmail.com",
                    NormalizedEmail = "LINDA1234@GMAIL.COM",
                    PasswordHash = hasher.HashPassword(null, defaultPassword),
                    ConcurrencyStamp = Guid.NewGuid().ToString(),
                    LastName = "Garde",
                    FirstName = "Linda",
                    MiddleName = "P.",
                    PhoneNumber = "",
                },
                 new User
                 {
                     Id = "8fa3f3e4-b8a2-4375-9dc8-91b6fbc55e4a",
                     UserName = "Java",
                     NormalizedUserName = "JAVA",
                     Email = "Java1234@gmail.com",
                     NormalizedEmail = "JAVA1234@GMAIL.COM",
                     PasswordHash = hasher.HashPassword(null, defaultPassword),
                     ConcurrencyStamp = Guid.NewGuid().ToString(),
                     LastName = "Java",
                     FirstName = "Sergio",
                     MiddleName = "C.",
                     PhoneNumber = "",
                 },
                  new User
                  {
                      Id = "a6866933-92a9-41e7-9100-8bee51ed0ada",
                      UserName = "John",
                      NormalizedUserName = "JOHN",
                      Email = "John1234@gmail.com",
                      NormalizedEmail = "JOHN1234@GMAIL.COM",
                      PasswordHash = hasher.HashPassword(null, defaultPassword),
                      ConcurrencyStamp = Guid.NewGuid().ToString(),
                      LastName = "Maliga",
                      FirstName = "John",
                      MiddleName = "O.",
                      PhoneNumber = "",
                  },
                   new User
                   {
                       Id = "cade94b1-d0d9-4ded-a46f-c8473d9fbc00",
                       UserName = "tan.si",
                       NormalizedUserName = "TAN.SI",
                       Email = "scibrahimtan@gmail.com",
                       NormalizedEmail = "SCRIBRAHIMTAN@GMAIL.COM",
                       PasswordHash = hasher.HashPassword(null, defaultPassword),
                       ConcurrencyStamp = Guid.NewGuid().ToString(),
                       LastName = "TAN",
                       FirstName = "Scheherazade",
                       MiddleName = "I.",
                       PhoneNumber = "09178663037",
                   },
                    new User
                    {
                        Id = "e1a3ac20-1d20-4f37-8826-242657a746c7",
                        UserName = "Dimaren",
                        NormalizedUserName = "DIMAREN",
                        Email = "Dimaren1234@gmail.com",
                        NormalizedEmail = "DIMAREN1234@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "Dimaren",
                        FirstName = "Ishmael",
                        MiddleName = "R.",
                        PhoneNumber = "",
                    },
                     new User
                     {
                         Id = "e9bcc340-e63f-40e6-8326-8fe86cbef923",
                         UserName = "Precious",
                         NormalizedUserName = "PRECIOUS",
                         Email = "Precious1234@gmail.com",
                         NormalizedEmail = "PRECIOUS1234@GMAIL.COM",
                         PasswordHash = hasher.HashPassword(null, defaultPassword),
                         ConcurrencyStamp = Guid.NewGuid().ToString(),
                         LastName = "Esquillo",
                         FirstName = "Precious Love",
                         MiddleName = "Y.",
                         PhoneNumber = "",
                     },
                     new User
                     {
                         Id = "18b4151f-bff9-4525-b787-7a7e009757c3",
                         UserName = "Singgon",
                         NormalizedUserName = "SINGGON",
                         Email = "Singgon1234@gmail.com",
                         NormalizedEmail = "SINGGON1234@GMAIL.COM",
                         PasswordHash = hasher.HashPassword(null, defaultPassword),
                         ConcurrencyStamp = Guid.NewGuid().ToString(),
                         LastName = "Singgon",
                         FirstName = "Bai Samirah",
                         MiddleName = "A.",
                         PhoneNumber = "",
                     },                   
                    new User
                    {
                        Id = "399f5e43-93d8-4a28-b113-d23eccd2ea15",
                        UserName = "mangansakan.norhan",
                        NormalizedUserName = "MANGANSAKAN.NORHAN",
                        Email = "npmangansakan@rocketmail.com",
                        NormalizedEmail = "NPMANGANSAKAN@ROCKETMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MANGANSAKAN",
                        FirstName = "NORHAN",
                        MiddleName = "PIANG",
                        PhoneNumber = "09166629909",
                    },
                    new User
                    {
                        Id = "e765e1f5-bc17-49b1-9c3f-8c5c2c18b420",
                        UserName = "arumpac.nurlinda",
                        NormalizedUserName = "ARUMPAC.NURLINDA",
                        Email = "nurlinda_06@yahoo.com",
                        NormalizedEmail = "NURLINDA_06@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ARUMPAC",
                        FirstName = "NURLINDA",
                        MiddleName = "PANGILAN",
                        PhoneNumber = "09177266885",
                    },
                    new User
                    {
                        Id = "b4d73e5f-f530-4a4d-9c3d-0b364236da6f",
                        UserName = "bedol.lintang",
                        NormalizedUserName = "BEDOL.LINTANG",
                        Email = "jrbedol@gmail.com",
                        NormalizedEmail = "JRBEDOL@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "BEDOL",
                        FirstName = "LINTANG",
                        MiddleName = "BUAN",
                        PhoneNumber = "09226218394",
                    },
                    new User
                    {
                        Id = "f8a17354-91b3-4c0e-9b71-d6af05f4e11e",
                        UserName = "kadil.ronald",
                        NormalizedUserName = "KADIL.RONALD",
                        Email = "rhkadil@gmail.com",
                        NormalizedEmail = "RHKADIL@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "KADIL",
                        FirstName = "RONALD",
                        MiddleName = "HIPONIA",
                        PhoneNumber = "09175333922",
                    },
                    new User
                    {
                        Id = "9b6d73e5-ff27-44bb-a9d0-f7c58b31c4a1",
                        UserName = "karao.mohamad",
                        NormalizedUserName = "KARAO.MOHAMAD",
                        Email = "madz.karao@gmail.com",
                        NormalizedEmail = "MADZ.KARAO@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "KARAO",
                        FirstName = "MOHAMAD",
                        MiddleName = "DUMBI",
                        PhoneNumber = "09363769315",
                    },
                    new User
                    {
                        Id = "a1f6d353-df11-4a17-b2be-49371b8c223d",
                        UserName = "astillero.adonis",
                        NormalizedUserName = "ASTILLERO.ADONIS",
                        Email = "don_astillero@yahoo.com",
                        NormalizedEmail = "DON_ASTILLERO@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ASTILLERO",
                        FirstName = "ADONIS",
                        MiddleName = "CHAN",
                        PhoneNumber = "09176261812",
                    },
                    new User
                    {
                        Id = "f2b28c8e-58cf-47b2-8245-33a7a98a7344",
                        UserName = "abantas.bbgirl",
                        NormalizedUserName = "ABANTAS.BBGIRL",
                        Email = "abantasfaizah@gmail.com",
                        NormalizedEmail = "ABANTASFAIZAH@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ABANTAS",
                        FirstName = "BBGIRL FAIZAH",
                        MiddleName = "SHARIF",
                        PhoneNumber = "09618235949",
                    },
                    new User
                    {
                        Id = "6db39f4a-9d19-4fc2-b3ab-2aa37851bb71",
                        UserName = "abubakar.anida",
                        NormalizedUserName = "ABUBAKAR.ANIDA",
                        Email = "anidaabubakar5@gmail.com",
                        NormalizedEmail = "ANIDAABUBAKAR5@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ABUBAKAR",
                        FirstName = "ANIDA",
                        MiddleName = "PENDALIDAY",
                        PhoneNumber = "09177234338",
                    },
                    new User
                    {
                        Id = "c54d18f2-9a21-4f72-92eb-1f5d6e8f58de",
                        UserName = "adang.alibasher",
                        NormalizedUserName = "ADANG.ALIBASHER",
                        Email = "bashegal23@gmail.com",
                        NormalizedEmail = "BASHEGAL23@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ADANG",
                        FirstName = "ALIBASHER",
                        MiddleName = "ABO",
                        PhoneNumber = "09369833653",
                    },
                    new User
                    {
                        Id = "a1a6e8f1-4749-4a8e-8f9b-0b6b2f05f38b",
                        UserName = "agting.laila",
                        NormalizedUserName = "AGTING.LAILA",
                        Email = "lailakaliaagting@gmail.com",
                        NormalizedEmail = "LAILAKALIAAGTING@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "AGTING",
                        FirstName = "LAILA",
                        MiddleName = "KALI",
                        PhoneNumber = "09177124579",
                    },
                    new User
                    {
                        Id = "f79e34aa-f6a2-4ff1-b2e0-4a7c8194e61c",
                        UserName = "akmad.amera",
                        NormalizedUserName = "AKMAD.AMERA",
                        Email = "miemarandakan@gmail.com",
                        NormalizedEmail = "MIEMARANDAKAN@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "AKMAD",
                        FirstName = "AMERA",
                        MiddleName = "MARANDACAN",
                        PhoneNumber = "09560537326",
                    },
                    new User
                    {
                        Id = "1b8a5144-b8a6-4df5-bb98-0136d7ebdf24",
                        UserName = "akmad.abdul",
                        NormalizedUserName = "AKMAD.ABDUL",
                        Email = "maraguia44@gmail.com",
                        NormalizedEmail = "MARAGUIA44@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "AKMAD",
                        FirstName = "ABDUL",
                        MiddleName = "MARAGUIAL",
                        PhoneNumber = "09209177429",
                    },
                    new User
                    {
                        Id = "6c8454ef-fd19-4db5-9f88-dcd7b13e5c55",
                        UserName = "alojipan.rosario",
                        NormalizedUserName = "ALOJIPAN.ROSARIO",
                        Email = "rosarioalojipan@gmail.com",
                        NormalizedEmail = "ROSARIOALOJIPAN@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ALOJIPAN",
                        FirstName = "ROSARIO",
                        MiddleName = "DELA CRUZ",
                        PhoneNumber = "09178202970",
                    },
                    new User
                    {
                        Id = "4f5b9c31-d406-4036-b8cd-37cb92d6b211",
                        UserName = "andal.yasser",
                        NormalizedUserName = "ANDAL.YASSER",
                        Email = "yashou_07@yahoo.com",
                        NormalizedEmail = "YASHOU_07@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ANDAL",
                        FirstName = "YASSER FARID",
                        MiddleName = "MAMA",
                        PhoneNumber = "09173085559",
                    },
                    new User
                    {
                        Id = "0b91d20a-0ab3-4820-b3f2-fbcf01c0af26",
                        UserName = "andamen.rahma",
                        NormalizedUserName = "ANDAMEN.RAHMA",
                        Email = "racsandamen13@gmail.com",
                        NormalizedEmail = "RACSANDAMEN13@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ANDAMEN",
                        FirstName = "RAHMA",
                        MiddleName = "KALID",
                        PhoneNumber = "09456829380",
                    },
                    new User
                    {
                        Id = "2489fce0-858f-43af-b82a-65ee42cb2e33",
                        UserName = "angas.al-jazzer",
                        NormalizedUserName = "ANGAS.AL-JAZZER",
                        Email = "aljazzerangas@yahoo.com",
                        NormalizedEmail = "ALJAZZERANGAS@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ANGAS",
                        FirstName = "AL-JAZZER",
                        MiddleName = "MAULANA",
                        PhoneNumber = "09179755770",
                    },
                    new User
                    {
                        Id = "5ff58cb5-9d0c-44b2-bc2a-5f96a3c9d621",
                        UserName = "arias.renante",
                        NormalizedUserName = "ARIAS.RENANTE",
                        Email = null,
                        NormalizedEmail = null,
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ARIAS",
                        FirstName = "RENANTE",
                        MiddleName = "ZIA",
                        PhoneNumber = null,
                    },
                    new User
                    {
                        Id = "cc505df2-3586-41a1-9d44-b5fc8f28e3a9",
                        UserName = "bangen.shiedhe",
                        NormalizedUserName = "BANGEN.SHIEDHE",
                        Email = "shiedhe@yahoo.com",
                        NormalizedEmail = "SHIEDHE@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "BANGEN",
                        FirstName = "SHIEDHE",
                        MiddleName = "KEMBUAN",
                        PhoneNumber = "09396526665",
                    },
                    new User
                    {
                        Id = "8ea08a3f-066a-41ac-9ef0-ffb47d3657d9",
                        UserName = "bantilan.danny",
                        NormalizedUserName = "BANTILAN.DANNY",
                        Email = "dannyfherbantilan@yahoo.com",
                        NormalizedEmail = "DANNYFHERBANTILAN@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "BANTILAN",
                        FirstName = "DANNY FHER",
                        MiddleName = "BANQUIAO",
                        PhoneNumber = "09272727645",
                    },
                    new User
                    {
                        Id = "c79be729-47b3-4907-88e1-0a67dd4e48b1",
                        UserName = "bassal.zahida",
                        NormalizedUserName = "BASSAL.ZAHIDA",
                        Email = "zahidabationgbassal2018@gmail.com",
                        NormalizedEmail = "ZAHIDABATIONGBASSAL2018@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "BASSAL",
                        FirstName = "ZAHIDA",
                        MiddleName = "BATIONG",
                        PhoneNumber = "09161012599",
                    },
                    new User
                    {
                        Id = "de17cb47-83e7-4a6b-b97c-13808e14a7ff",
                        UserName = "bones.anabelle",
                        NormalizedUserName = "BONES.ANABELLE",
                        Email = "acocalbo@yahoo.com",
                        NormalizedEmail = "ACOCALBO@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "BONES",
                        FirstName = "ANABELLE",
                        MiddleName = "COCAL",
                        PhoneNumber = "09483207824",
                    },
                    new User
                    {
                        Id = "0ed1f88a-8859-4d6c-9a1f-84aaf19cc45c",
                        UserName = "bonite.emelia",
                        NormalizedUserName = "BONITE.EMELIA",
                        Email = "amybonite09@yahoo.com",
                        NormalizedEmail = "AMYBONITE09@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "BONITE",
                        FirstName = "EMELIA",
                        MiddleName = "YU",
                        PhoneNumber = "09055207141",
                    },
                    new User
                    {
                        Id = "74c35794-54d9-44a4-baf0-b8fa23e2d481",
                        UserName = "caldea.maylene",
                        NormalizedUserName = "CALDEA.MAYLENE",
                        Email = "Mulcaldea@gmail.com",
                        NormalizedEmail = "MULCALDEA@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "CALDEA",
                        FirstName = "MAYLENE",
                        MiddleName = "ULOG",
                        PhoneNumber = "09953048269",
                    },
                    new User
                    {
                        Id = "53a2b071-d36f-4f1f-bf8e-3f7dbf7b8c7b",
                        UserName = "candao.abdulbayan",
                        NormalizedUserName = "CANDÃO.ABDULBAYAN",
                        Email = "naughty_candao@yahoo.com",
                        NormalizedEmail = "NAUGHTY_CANDAO@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "CANDAO",
                        FirstName = "ABDULBAYAN",
                        MiddleName = "BAYAO",
                        PhoneNumber = "09564021897",
                    },
                    new User
                    {
                        Id = "28a2a313-bc8e-4225-b8c2-85c2935b315e",
                        UserName = "castillano.marc",
                        NormalizedUserName = "CASTILLANO.MARC",
                        Email = "marcrejohncastillano@gmail.com",
                        NormalizedEmail = "MARCREJOHNCASTILLANO@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "CASTILLANO",
                        FirstName = "MARC REJOHN",
                        MiddleName = "BALLARES",
                        PhoneNumber = "09959283775",
                    },
                    new User
                    {
                        Id = "35159a7c-2120-46f6-9135-8a8469b9c7b1",
                        UserName = "castillon.jobert",
                        NormalizedUserName = "CASTILLON.JOBERT",
                        Email = null,
                        NormalizedEmail = null,
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "CASTILLON",
                        FirstName = "JOBERT",
                        MiddleName = "ARMADA",
                        PhoneNumber = "09395055897",
                    },
                    new User
                    {
                        Id = "ec4219b7-dfc6-4966-bf2a-3f1eecf17391",
                        UserName = "cuyong.anthony",
                        NormalizedUserName = "CUYONG.ANTHONY",
                        Email = "rndmpa@gmail.com",
                        NormalizedEmail = "RNDMPA@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "CUYONG",
                        FirstName = "ANTHONY",
                        MiddleName = "CULAB",
                        PhoneNumber = "09453040405",
                    },
                    new User
                    {
                        Id = "1a9d8654-1c19-4b60-9491-4e33c176cc64",
                        UserName = "delosreyes.gloria",
                        NormalizedUserName = "DELOSREYES.GLORIA",
                        Email = "gloriacalubiran79@gmail.com",
                        NormalizedEmail = "GLORIACALUBIRAN79@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "DE LOS REYES",
                        FirstName = "GLORIA",
                        MiddleName = "CALUBIRAN",
                        PhoneNumber = "09363304534",
                    },
                     new User
                     {
                         Id = "1a9d8654-1c19-4b50-9431-4e23c174cc60",
                         UserName = "bilao.abdulhanif",
                         NormalizedUserName = "BILAO.ABDULHANIF",
                         Email = "Biloa1234@gmail.com",
                         NormalizedEmail = "BILAO1234@GMAIL.COM",
                         PasswordHash = hasher.HashPassword(null, defaultPassword),
                         ConcurrencyStamp = Guid.NewGuid().ToString(),
                         LastName = "Bilao",
                         FirstName = "Andul Hanif",
                         MiddleName = "B.",
                         PhoneNumber = "",
                     }, 
                     new User
                     {
                         Id = "2z9f8451-1n19-4b50-8432-4e23c164cs51",
                         UserName = "caoagdan.socorro",
                         NormalizedUserName = "CAOAGDAN.SOCORRO",
                         Email = "Caoagdan1234@gmail.com",
                         NormalizedEmail = "CAOAGDAN1234@GMAIL.COM",
                         PasswordHash = hasher.HashPassword(null, defaultPassword),
                         ConcurrencyStamp = Guid.NewGuid().ToString(),
                         LastName = "Caoagdan",
                         FirstName = "Socorro",
                         MiddleName = "A.",
                         PhoneNumber = "",
                     },
                     new User
                     {
                         Id = "9c49e0f2-4cb0-45b1-9f0e-4fbd24d25368",
                         UserName = "enlayoapaap.honeygrace",
                         NormalizedUserName = "ENLAYOAPAAP.HONEYGRACE",
                         Email = "graceenlayo@gmail.com",
                         NormalizedEmail = "GRACEENLAYO@GMAIL.COM",
                         PasswordHash = hasher.HashPassword(null, defaultPassword),
                         ConcurrencyStamp = Guid.NewGuid().ToString(),
                         LastName = "ENLAYO-APA-AP",
                         FirstName = "HONEY GRACE",
                         MiddleName = "ROMASANTA",
                         PhoneNumber = "09754948544",
                     },
                    new User
                    {
                        Id = "33a13c76-041f-4d68-8f67-41b7dd60c408",
                        UserName = "esmundo.henesijem",
                        NormalizedUserName = "ESMUNDO.HENESIJEM",
                        Email = "henesijesmundo27@gmail.com",
                        NormalizedEmail = "HENESIJESMUNDO27@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ESMUNDO",
                        FirstName = "HENESI JEM",
                        MiddleName = "GAUDIANO",
                        PhoneNumber = "09354975202",
                    },
                    new User
                    {
                        Id = "43cd6e17-9d86-4cb9-8d84-298e43a23450",
                        UserName = "factora.jesryllleana",
                        NormalizedUserName = "FACTORA.JESRYLLLEANA",
                        Email = "jesryll.tupas@yahoo.com",
                        NormalizedEmail = "JESRYLL.TUPAS@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "FACTORA",
                        FirstName = "JESRYLL LEANA",
                        MiddleName = "TUPAS",
                        PhoneNumber = "09176111210",
                    },
                    new User
                    {
                        Id = "c77b5df0-836a-4f9e-9f29-d2f6c6cf4074",
                        UserName = "ferrer.cheryl",
                        NormalizedUserName = "FERRER.CHERYL",
                        Email = "cherfer22@yahoo.com",
                        NormalizedEmail = "CHERFER22@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "FERRER",
                        FirstName = "CHERYL",
                        MiddleName = "MAGBANUA",
                        PhoneNumber = "09276048113",
                    },
                    new User
                    {
                        Id = "5d8a2197-b38b-40b2-940a-845e2a44b622",
                        UserName = "go.resilda",
                        NormalizedUserName = "GO.RESILDA",
                        Email = "resildago1212@gmail.com",
                        NormalizedEmail = "RESILDAGO1212@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "GO",
                        FirstName = "RESILDA",
                        MiddleName = "BAGGAYAN",
                        PhoneNumber = "09062249400",
                    },
                    new User
                    {
                        Id = "c79c6433-d1ad-46a3-ae87-84edb44476de",
                        UserName = "gonzales.renette",
                        NormalizedUserName = "GONZALES.RENETTE",
                        Email = "rendtesy0620@gmail.com",
                        NormalizedEmail = "RENDTSEY0620@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "GONZALES",
                        FirstName = "RENETTE",
                        MiddleName = "SUDARIO",
                        PhoneNumber = "09166248783",
                    },
                    new User
                    {
                        Id = "f03cf528-c2a5-4820-91a5-6821dc5350f8",
                        UserName = "sero.gabriel",
                        NormalizedUserName = "SERO.GABRIEL",
                        Email = "espurakoy@yahoo.com",
                        NormalizedEmail = "ESPURAKOY@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "SERO",
                        FirstName = "GABRIEL",
                        MiddleName = "BLANCO",
                        PhoneNumber = "09177239443",
                    },
                    new User
                    {
                        Id = "5f33b779-c424-4e4d-89a9-7b8e5ac3e98d",
                        UserName = "sabrine.jarrett",
                        NormalizedUserName = "SABRINE.JARRETT",
                        Email = "jettFTS@gmail.com",
                        NormalizedEmail = "JETTFTS@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "SABRINE",
                        FirstName = "JARRETT",
                        MiddleName = "DORONILLA",
                        PhoneNumber = "09162012248",
                    },
                    new User
                    {
                        Id = "baf0a172-7e0a-4999-8c03-8f9bfb62150b",
                        UserName = "salik.faisal",
                        NormalizedUserName = "SALIK.FAISAL",
                        Email = null,
                        NormalizedEmail = null,
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "SALIK",
                        FirstName = "FAISAL",
                        MiddleName = "ONG",
                        PhoneNumber = "09773262708",
                    },
                    new User
                    {
                        Id = "88a1a0b3-943d-47a2-b0bb-f1c8763acaf4",
                        UserName = "soriano.gerald",
                        NormalizedUserName = "SORIANO.GERALD",
                        Email = "tardz03@yahoo.com",
                        NormalizedEmail = "TARDZ03@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "SORIANO",
                        FirstName = "GERALD",
                        MiddleName = "VEN",
                        PhoneNumber = "09224339675",
                    },
                    new User
                    {
                        Id = "0ff9af54-f57a-4d1b-a2d6-679b3a4b8c30",
                        UserName = "salvatierra.ma.abigail",
                        NormalizedUserName = "SALVATIERRA.MA.ABIGAIL",
                        Email = "abigailsaveland@gmail.com",
                        NormalizedEmail = "ABIGAILSAVELAND@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "SALVATIERRA",
                        FirstName = "MA. ABIGAIL",
                        MiddleName = "YU",
                        PhoneNumber = "09088931724",
                    },
                    new User
                    {
                        Id = "59b4a3e6-30c2-4a8c-8851-78b95cf11f5b",
                        UserName = "sampulna.jomedelle",
                        NormalizedUserName = "SAMPULNA.JOMEDELLE",
                        Email = "jomedellesampulna13@gmail.com",
                        NormalizedEmail = "JOMEDELLESAMPULNA13@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "SAMPULNA",
                        FirstName = "JOMEDELLE",
                        MiddleName = "CHIO",
                        PhoneNumber = "09673774366",
                    },
                    new User
                    {
                        Id = "3db6b5af-4b42-4747-a3f0-3a60b3e36a56",
                        UserName = "sapi.terryjane",
                        NormalizedUserName = "SAPI.TERRYJANE",
                        Email = "omaldetj9@yahoo.com",
                        NormalizedEmail = "OMALDETJ9@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "SAPI",
                        FirstName = "TERRY JANE",
                        MiddleName = "OMALDE",
                        PhoneNumber = "09458244916",
                    },
                    new User
                    {
                        Id = "7gf2b7zj-4b42-2476-f3f3-1x72b3e34aq68",
                        UserName = "saliling.floredliza",
                        NormalizedUserName = "SALILING.FLOREDLIZA",
                        Email = "saliling1234@yahoo.com",
                        NormalizedEmail = "SALILING@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "Saliling-Alta",
                        FirstName = "Floredliza",
                        MiddleName = "J.",
                        PhoneNumber = "",
                    },
                    new User
                    {
                        Id = "b83670e3-3d7c-40a4-8d07-5a3c3f6bde91",
                        UserName = "gratuito.johnpaul",
                        NormalizedUserName = "GRATUITO.JOHNPAUL",
                        Email = "paogratuito@gmail.com",
                        NormalizedEmail = "PAOGRATUITO@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "GRATUITO",
                        FirstName = "JOHN PAUL",
                        MiddleName = "CHOA KHAO UY",
                        PhoneNumber = "09177027392",
                    },
                    new User
                    {
                        Id = "3a4c88b0-5f73-41f0-82e7-255e19e8d9d1",
                        UserName = "gumapac.aileen",
                        NormalizedUserName = "GUMAPAC.AILEEN",
                        Email = "leyn0426@yahoo.com",
                        NormalizedEmail = "LEYN0426@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "GUMAPAC",
                        FirstName = "AILEEN",
                        MiddleName = "SANTIAGO",
                        PhoneNumber = "09274449665",
                    },
                    new User
                    {
                        Id = "c0b41f2c-0f8d-4a53-b0a9-5cfa02b6a851",
                        UserName = "ismael.amirhussein",
                        NormalizedUserName = "ISMAEL.AMIRHUSSEIN",
                        Email = "jaheerhusseinismael@gmail.com",
                        NormalizedEmail = "JAHEERHUSSEINISMAEL@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ISMAEL",
                        FirstName = "AMIR HUSSEIN",
                        MiddleName = "MACAPENDENG",
                        PhoneNumber = "09564020491",
                    },
                    new User
                    {
                        Id = "c171e56e-b2e0-43f2-91f1-8f258417bc3d",
                        UserName = "ibrahimdumama.sharinah",
                        NormalizedUserName = "IBRAHIMDUMAMA.SHARINAH",
                        Email = "shingdumama@gmail.com",
                        NormalizedEmail = "SHINGDUMAMA@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "IBRAHIM-DUMAMA",
                        FirstName = "SHARINAH",
                        MiddleName = "CATALAN",
                        PhoneNumber = "09177263399",
                    },
                    new User
                    {
                        Id = "43f6a708-995c-4a07-9e90-6d0a5efc32d5",
                        UserName = "juanday.baiyasmin",
                        NormalizedUserName = "JUANDAY.BAIYASMIN",
                        Email = "baiyasminjaynonjuanday@gmail.com",
                        NormalizedEmail = "BAIYASMINJAYNONJUANDAY@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "JUANDAY",
                        FirstName = "BAI YASMIN",
                        MiddleName = "JAYNON",
                        PhoneNumber = "09260474812",
                    },
                    new User
                    {
                        Id = "21d7b7dc-3425-464f-96d5-f6784b19b4cf",
                        UserName = "lu.leonita",
                        NormalizedUserName = "LU.LEONITA",
                        Email = "lenzkylu@gmail.com",
                        NormalizedEmail = "LENZKYLU@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "LU",
                        FirstName = "LEONITA",
                        MiddleName = "CHUA",
                        PhoneNumber = "09178732580",
                    },
                    new User
                    {
                        Id = "c8dc080e-2c5f-4a8e-b0e0-9c29dc45a31f",
                        UserName = "lu.rowena",
                        NormalizedUserName = "LU.ROWENA",
                        Email = "rbmaputi@gmail.com",
                        NormalizedEmail = "RBMAPUTI@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "LU",
                        FirstName = "ROWENA",
                        MiddleName = "MAPUTI",
                        PhoneNumber = "09173000155",
                    },
                    new User
                    {
                        Id = "13ab0a0e-5d9a-4e53-a5f0-5cb11a775fe3",
                        UserName = "luces.rosalie",
                        NormalizedUserName = "LUCES.ROSALIE",
                        Email = "rosalieluces05@gmail.com",
                        NormalizedEmail = "ROSALIELUCES05@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "LUCES",
                        FirstName = "ROSALIE",
                        MiddleName = "OREJUDOS",
                        PhoneNumber = "09109099656",
                    },
                    new User
                    {
                        Id = "a2a9b64b-1b54-4c49-90e2-4dbf1e59a98e",
                        UserName = "mabang.sigrid",
                        NormalizedUserName = "MABANG.SIGRID",
                        Email = "mabangsigrid@gmail.com",
                        NormalizedEmail = "MABANGSIGRID@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MABANG",
                        FirstName = "SIGRID",
                        MiddleName = "BARAGUIR",
                        PhoneNumber = "09351488175",
                    },
                    new User
                    {
                        Id = "49180f4a-cbe7-489b-8fd1-901e79dfe2f5",
                        UserName = "maglangit.sittieaneza",
                        NormalizedUserName = "MAGLANGIT.SITTIEANEZA",
                        Email = "sacamaglangit.md@gmail.com",
                        NormalizedEmail = "SACAMAGLANGIT.MD@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MAGLANGIT",
                        FirstName = "SITTIE ANEZA CAMILLE",
                        MiddleName = "AMAD",
                        PhoneNumber = "09989913196",
                    },
                    new User
                    {
                        Id = "dcf663a4-36f5-4fd6-b124-bae31e0c9e2e",
                        UserName = "malana.jayjay",
                        NormalizedUserName = "MALANA.JAYJAY",
                        Email = "jayjay_malana@hotmail.com",
                        NormalizedEmail = "JAYJAY_MALANA@HOTMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MALANA",
                        FirstName = "JAY-JAY",
                        MiddleName = "MALANNAG",
                        PhoneNumber = "09274171288",
                    },
                    new User
                    {
                        Id = "17793347-1bfa-4526-a0af-0ffcf374aa9a",
                        UserName = "manaois.marjorene",
                        NormalizedUserName = "MANAOIS.MARJORENE",
                        Email = "marjorenecorpuz@yahoo.com",
                        NormalizedEmail = "MARJORENECORPUZ@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MANAOIS",
                        FirstName = "MARJORENE",
                        MiddleName = "CORPUZ",
                        PhoneNumber = "09072856158",
                    },
                    new User
                    {
                        Id = "6f34a16a-6e68-4d8b-9f6a-0e0c07a09ed8",
                        UserName = "mamaluba.farizah",
                        NormalizedUserName = "MAMALUBA.FARIZAH",
                        Email = "farizahm@yahoo.com",
                        NormalizedEmail = "FARIZAHM@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MAMALUBA",
                        FirstName = "FARIZAH",
                        MiddleName = "MODIARAT",
                        PhoneNumber = "09168372024",
                    },
                    new User
                    {
                        Id = "a6b59fd2-75eb-457e-90ea-d1d419da5f6d",
                        UserName = "mangulamas.honeylet",
                        NormalizedUserName = "MANGULAMAS.HONEYLET",
                        Email = "hunnyresquites88@yahoo.com",
                        NormalizedEmail = "HUNNYRESQUITES88@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MANGULAMAS",
                        FirstName = "HONEYLET",
                        MiddleName = "RESQUITES",
                        PhoneNumber = "09776146365",
                    },
                    new User
                    {
                        Id = "53ac9d08-f52f-4a25-92d7-10de53f612fa",
                        UserName = "martinez.rodelyn",
                        NormalizedUserName = "MARTINEZ.RODELYN",
                        Email = "rodelynmartinez619@gmail.com",
                        NormalizedEmail = "RODELYNMARTINEZ619@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MARTINEZ",
                        FirstName = "RODELYN",
                        MiddleName = "CORTEZ",
                        PhoneNumber = "09177188038",
                    },
                    new User
                    {
                        Id = "827e71e5-479c-47a7-8f91-16327825a02d",
                        UserName = "meditar.farida",
                        NormalizedUserName = "MEDITAR.FARIDA",
                        Email = "faridaolama@gmail.com",
                        NormalizedEmail = "FARIDAOLAMA@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MEDITAR",
                        FirstName = "FARIDA",
                        MiddleName = "OLAMA",
                        PhoneNumber = "09606059079",
                    },
                    new User
                    {
                        Id = "dfb15a5f-9f4e-48e6-b781-f4a62c5bfb0a",
                        UserName = "midtimbang.bebot",
                        NormalizedUserName = "MIDTIMBANG.BEBOT",
                        Email = "midtimbangbebot@gmail.com",
                        NormalizedEmail = "MIDTIMBANGBEBOT@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MIDTIMBANG",
                        FirstName = "BEBOT",
                        MiddleName = "USOP",
                        PhoneNumber = "09755272044",
                    },
                    new User
                    {
                        Id = "12183b62-26ee-459b-a859-88a94e86c117",
                        UserName = "mojado.jocelyn",
                        NormalizedUserName = "MOJADO.JOCELYN",
                        Email = "NA",
                        NormalizedEmail = "NA",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "MOJADO",
                        FirstName = "JOCELYN",
                        MiddleName = "BAJAO",
                        PhoneNumber = "NA",
                    },
                    new User
                    {
                        Id = "ef529a6b-b381-4db1-a204-913ba73a6721",
                        UserName = "olivo.ariel",
                        NormalizedUserName = "OLIVO.ARIEL",
                        Email = "iamarielolivo@gmail.com",
                        NormalizedEmail = "IAMARIELOLIVO@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "OLIVO",
                        FirstName = "ARIEL",
                        MiddleName = "MELOCOTON",
                        PhoneNumber = "09084724708",
                    },
                    new User
                    {
                        Id = "969fb51f-26aa-4637-8a8a-96247c7a67a4",
                        UserName = "omar.hasmia",
                        NormalizedUserName = "OMAR.HASMIA",
                        Email = "hasmiamdo@gmail.com",
                        NormalizedEmail = "HASMIAMDO@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "OMAR",
                        FirstName = "HASMIA",
                        MiddleName = "DATUMANONG",
                        PhoneNumber = "09365268695",
                    },
                    new User
                    {
                        Id = "b5870b06-0240-4d35-a6b1-54a76c1e09fc",
                        UserName = "ondoy.marivette",
                        NormalizedUserName = "ONDOY.MARIVETTE",
                        Email = "apple_foj@yahoo.com",
                        NormalizedEmail = "APPLE_FOJ@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ONDOY",
                        FirstName = "MARIVETTE",
                        MiddleName = "TABUGO",
                        PhoneNumber = "09177228527",
                    },
                    new User
                    {
                        Id = "bb22c692-bc14-44db-9a6e-5b0196c9a8c2",
                        UserName = "orig.monaliza",
                        NormalizedUserName = "ORIG.MONALIZA",
                        Email = "origmonaliza@gmail.com",
                        NormalizedEmail = "ORIGMONALIZA@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ORIG",
                        FirstName = "MONALIZA",
                        MiddleName = "NOR",
                        PhoneNumber = "09274704538",
                    },
                    new User
                    {
                        Id = "5b7ff0c8-b6f9-489c-9f1d-9faadf9e6c6f",
                        UserName = "padilla.jorge",
                        NormalizedUserName = "PADILLA.JORGE",
                        Email = "hor_he@yahoo.com",
                        NormalizedEmail = "HOR_HE@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "PADILLA",
                        FirstName = "JORGE",
                        MiddleName = "LAMPITOC",
                        PhoneNumber = "09177900470",
                    },
                    new User
                    {
                        Id = "d65e3f58-b23d-4b83-8b15-15e66565d29f",
                        UserName = "pantaran.sandra",
                        NormalizedUserName = "PANTARAN.SANDRA",
                        Email = "shpagayao@gmail.com",
                        NormalizedEmail = "SHPAGAYAO@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "PANTARAN",
                        FirstName = "SANDRA",
                        MiddleName = "PAGAYAO",
                        PhoneNumber = "09163771505",
                    },
                    new User
                    {
                        Id = "a1e10c26-4d1d-4f9e-9378-1382457c82ad",
                        UserName = "pinguiaman.baitayan",
                        NormalizedUserName = "PINGUIAMAN.BAITAYAN",
                        Email = "beeyoupee@gmail.com",
                        NormalizedEmail = "BEEYOUPEE@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "PINGUIAMAN",
                        FirstName = "BAITAYAN",
                        MiddleName = "UNTONG",
                        PhoneNumber = "09056377715",
                    },
                    new User
                    {
                        Id = "dfc40941-0cfb-46ed-8991-e285aa08c20e",
                        UserName = "quinto.jennifer",
                        NormalizedUserName = "QUINTO.JENNIFER",
                        Email = "quinto.jennifer82@gmail.com",
                        NormalizedEmail = "QUINTO.JENNIFER82@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "QUINTO",
                        FirstName = "JENNIFER",
                        MiddleName = "CATBAGAN",
                        PhoneNumber = "09272708149",
                    },
                    new User
                    {
                        Id = "f23ac0c6-68ac-41c8-94ff-383acbfc3e41",
                        UserName = "real.vivian",
                        NormalizedUserName = "REAL.VIVIAN",
                        Email = "estrellavsreal@yahoo.com",
                        NormalizedEmail = "ESTRELLAVSREAL@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "REAL",
                        FirstName = "VIVIAN",
                        MiddleName = "SARATAO",
                        PhoneNumber = "09171027173",
                    },
                    new User
                    {
                        Id = "50e3ff41-8195-4d52-805a-d55efb68f08a",
                        UserName = "suico.neilalfonso",
                        NormalizedUserName = "SUICO.NEILALFONSO",
                        Email = "lienocius@gmail.com",
                        NormalizedEmail = "LIENOCIUS@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "SUICO",
                        FirstName = "NEIL ALFONSO",
                        MiddleName = "VIRAY",
                        PhoneNumber = "09260398619",
                    },
                    new User
                    {
                        Id = "55c79a0c-4f48-472f-9d13-1801e2e5c167",
                        UserName = "superales.maryjane",
                        NormalizedUserName = "SUPERALES.MARYJANE",
                        Email = "janesuperales27@gmail.com",
                        NormalizedEmail = "JANESUPERALES27@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "SUPERALES",
                        FirstName = "MARY JANE",
                        MiddleName = "ORTEGA",
                        PhoneNumber = "09162424748",
                    },
                    new User
                    {
                        Id = "2e889d55-159e-44a0-b9c9-44cc9f25c66b",
                        UserName = "tocao.suzette",
                        NormalizedUserName = "TOCAO.SUZETTE",
                        Email = "suzettetocao@gmail.com",
                        NormalizedEmail = "SUZETTE TOCAO@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "TOCAO",
                        FirstName = "SUZETTE",
                        MiddleName = "COMPLETANO",
                        PhoneNumber = "09219908520",
                    },
                    new User
                    {
                        Id = "2ec1e24b-50c6-48b7-8e9c-18c64a42e172",
                        UserName = "usman.aswarfy",
                        NormalizedUserName = "USMAN.ASWARFY",
                        Email = "ashmatik23@gmail.com",
                        NormalizedEmail = "ASHMATIK23@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "USMAN",
                        FirstName = "ASWARFY",
                        MiddleName = "MOHAMAD",
                        PhoneNumber = "09173383890",
                    },
                    new User
                    {
                        Id = "87234d0c-41c3-44e5-8cb7-5d7a7a9209c8",
                        UserName = "usmanbali.hamida",
                        NormalizedUserName = "USMANBALI.HAMIDA",
                        Email = "hamidadubali@gmail.com",
                        NormalizedEmail = "HAMIDADUBALI@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "USMAN-BALI",
                        FirstName = "HAMIDA",
                        MiddleName = "DATUMANONG",
                        PhoneNumber = "09368159393",
                    },
                    new User
                    {
                        Id = "39987409-6b12-4a73-a9a3-61c7f117dcab",
                        UserName = "vasay.claurence",
                        NormalizedUserName = "VASAY.CLAURENCE",
                        Email = "claurencevasay@gmail.com",
                        NormalizedEmail = "CLAURENCEVASAY@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "VASAY",
                        FirstName = "CLAURENCE",
                        MiddleName = "ACHAS",
                        PhoneNumber = "09555765345",
                    },
                    new User
                    {
                        Id = "56731842-6b12-9a46-k9h2-61c7f212hyex",
                        UserName = "silvestre.chrislenlee",
                        NormalizedUserName = "SILVESTRE.CHRISLENLEE",
                        Email = "Silvestre1234@gmail.com",
                        NormalizedEmail = "SILVESTRE1234@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "Silvestre",
                        FirstName = "Chrislen Lee",
                        MiddleName = "C.",
                        PhoneNumber = "",
                    },
                    new User
                    {
                        Id = "c8463e9f-8ac6-40c3-91b1-2385f6a91eb4",
                        UserName = "villa.russelkirk",
                        NormalizedUserName = "VILLA.RUSSELKIRK",
                        Email = "holy_voltz771989@yahoo.com",
                        NormalizedEmail = "HOLY_VOLTZ771989@YAHOO.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "VILLA",
                        FirstName = "RUSSEL KIRK",
                        MiddleName = "GUALINGCO",
                        PhoneNumber = "09095412351",
                    },
                    new User
                    {
                        Id = "abfc1b6f-9f29-44dd-9c45-cdcddaa6eb83",
                        UserName = "villanueva.ruby",
                        NormalizedUserName = "VILLANUEVA.RUBY",
                        Email = "ruby012770@outlook.com",
                        NormalizedEmail = "RUBY012770@OUTLOOK.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "VILLANUEVA",
                        FirstName = "RUBY",
                        MiddleName = "ELEVAZO",
                        PhoneNumber = "09173510613",
                    },
                    new User
                    {
                        Id = "db7fba3d-88fc-47cf-b119-f868d9196f02",
                        UserName = "villarosa.ronnie",
                        NormalizedUserName = "VILLAROSA.RONNIE",
                        Email = "ronfaith2003@gmail.com",
                        NormalizedEmail = "RONFAITH2003@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "VILLAROSA",
                        FirstName = "RONNIE",
                        MiddleName = "GREGORIO",
                        PhoneNumber = "09956598896",
                    },
                    new User
                    {
                        Id = "7cfd0766-f3d3-47aa-9a48-53d437d6c232",
                        UserName = "zaman.wahida",
                        NormalizedUserName = "ZAMAN.WAHIDA",
                        Email = "wahidamaniala@gmail.com",
                        NormalizedEmail = "WAHIDAMANIALA@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ZAMAN",
                        FirstName = "WAHIDA",
                        MiddleName = "MANIALA",
                        PhoneNumber = "09065830887",
                    },
                    new User
                    {
                        Id = "9821dbf5-0f70-4630-8c68-f2077a3abf08",
                        UserName = "zambrano.jhoanamarie",
                        NormalizedUserName = "ZAMBRANO.JHOANAMARIE",
                        Email = "ZAMBRANO.REHABMD@GMAIL.COM",
                        NormalizedEmail = "ZAMBRANO.REHABMD@GMAIL.COM",
                        PasswordHash = hasher.HashPassword(null, defaultPassword),
                        ConcurrencyStamp = Guid.NewGuid().ToString(),
                        LastName = "ZAMBRANO",
                        FirstName = "JHOANA MARIE",
                        MiddleName = "JUANEZA",
                        PhoneNumber = "09178470437",
                    }

        );
    }
}
